### ISSUE TITLE
error folders?

### ISSUE THREAD

**Issue by pipes80-collab** [Saancreed/wine-nvml#12]
why this? 
build-mingw32/src/nvml.dll → ${compatdata}/pfx/drive_c/windows/syswow64/nvml.dll
build-mingw64/src/nvml.dll → ${compatdata}/pfx/drive_c/windows/system32/nvml.dll

files in build-mingw64 in system32 and viceversa?

**Comment by Saancreed** [comment]
It's like this because on 64-bit Windows systems and in win64 Wine prefixes `system32` contains 64-bit libraries and `syswow64` contains 32-bit libraries, so we want our 64-bit library in `system32` and 32-bit library in `syswow64`.

I hope this makes sense for you because it barely does for me. Something about `syswow64` meaning "System Windows(32) on Windows64" and `system32` being for libraries with native OS bitness except it has 32 suffix ~~for extra confusion~~ because adding one was cool back when it was invented? I'm not sure to be honest.
