### ISSUE TITLE
Wow64 experimental

### ISSUE THREAD

**Issue by SveSop** [Saancreed/wine-nvml#14]
Since Wine is moving towards using wow64 mode for wine, the issue of getting stuff like NVML to work is at hand imo..

I started working on this here : https://github.com/SveSop/wine-nvml/tree/wow64

It does compile and actually loads/accept calls when using Wine compiled as "wow64"... but there is ofc loads of issues to iron out - like the fact that DXVK-NVAPI does not get a "correct  handle" and stuff like that. I assume this is due to pointer differences between 32<->64 bit for `nvmldevice_t` perhaps?

I looked at wine implementations they did here:
https://gitlab.winehq.org/wine/wine/-/commit/e9c065e590133d5c19365c77b48eda99b7be367e
https://gitlab.winehq.org/wine/wine/-/commit/7693fb80912ad53128200515e236b71398a8e61f

There is also quite a bit to learn on wine's opengl32 implementation of this. (Similar with LOADS of function calls).

Just from the minor hacking i did so far, it actually seems like `__wine_unix_call_wow64_funcs` got "automagically picked up" as the correct thing to do for this "unix call helper" when running in 32-bit. So the next question is if ALL the functions need to be converted to `wow64_` functions instead of `wine_` functions for this "mode". Not sure if all functions using some sort of pointer needs to - although it may be quite likely.

I am sure you have a much better idea of this than me - especially when it comes to automate this in the `make_nvml` script.

PS. I did not want to create a PR on this for your master branch, but if you can choose to pull this to a new branch if i do, im happy to do it.. Let me know 😄

**Comment by Saancreed** [comment]
At the very least, updating `unixlib.h` and switching to `__wine_init_unix_call` + `WINE_UNIX_CALL` is something I would gladly accept (and in fact, I planned to do once I was sure that this either won't break Wine/Proton 7.0 or that I can afford to drop support for anything older than 8.0).

> It does compile and actually loads/accept calls when using Wine compiled as "wow64"... but there is ofc loads of issues to iron out - like the fact that DXVK-NVAPI does not get a "correct handle" and stuff like that. I assume this is due to pointer differences between 32<->64 bit for `nvmldevice_t` perhaps?

Yes, I believe that is the primary issue here. We are handed a struct that contains a pointer to a value we are supposed to set. The pointer being 32-bit shouldn't matter as long as the address space remains the same. However, the _value_ itself (of type `nvmlDevice_t`) also changes size because it's actually an opaque pointer type. So we cannot loselessly return a 64-bit number in 32-bit variable without losing information we will later need to actually call further NVML functions on that device. Looking at winevulkan code, there is a lot of handle wrapping and unwrapping being done that, as far as I understand, allows Wine to sidestep this, but it looks damn complicated to understand or replicate.

> So the next question is if ALL the functions need to be converted to `wow64_` functions instead of `wine_` functions for this "mode". Not sure if all functions using some sort of pointer needs to - although it may be quite likely.

That "all functions using some sort of pointer" would be my understanding as well, except in case of NVML that would mean _pretty much all functions_.

However, as #13 has shown us, exposing 32-bit NVML causes more harm than good so I'm not sure if it's a good idea to spend a lot of time figuring this out if all we get in return is 32-bit applications crashing.

(That also reminded me to take a look at GPUShark2 thingy you mentioned there :sweat_smile:)

> PS. I did not want to create a PR on this for your master branch, but if you can choose to pull this to a new branch if i do, im happy to do it.. Let me know 😄

Yes for `unixlib.h`, `__wine_init_unix_call` and `WINE_UNIX_CALL`, no for wow64 stuff, at least until we figure out handle wrapping and with NVML not having a nice XML to parse, this will probably be painful.

**Comment by SveSop** [comment]
Added a PR using only the Unix call helpers, and briefly from testing GPU Caps Viewer and GPUShark2, it works as before for regularly compiled Wine (ie. separately 32/64-bit compiles) AND it works for 64-bit apps for wow64 compiled wine (TKG-8.15)

Only thing happening when running GPU Caps Viewer (that is 32-bit) in wow64 experimental mode with this is that the lib fails to load. and NVAPI logs "No implementation" (due to NVML not working) for those calls using NVML, and NVML logs:
```
trace:nvml:DLLMain (6ECC0000, 1, 00000000)
trace:nvml:DLLMain (6ECC0000, 0, 00000000)
```
This is due to 32-bit nvml.so is not loaded. (Checking with strace confirms no attempt to load nvml.so in this wow64 mode).

And i guess you are very right about this being a LOT of the NVML calls using pointers in general, and will probably need conversion. Maybe it is easier to use the script to generate a custom `wow64_nvml_private.h` header file with `ULONG` pointers like Wine seem to have done for their seperate "params" usage? So it is more automated, but not adding ALL the calls that much of a manual labor?

**Comment by Saancreed** [comment]
> Added a PR using only the Unix call helpers, and briefly from testing GPU Caps Viewer and GPUShark2, it works as before for regularly compiled Wine (ie. separately 32/64-bit compiles) AND it works for 64-bit apps for wow64 compiled wine (TKG-8.15)
> 
> Only thing happening when running GPU Caps Viewer (that is 32-bit) in wow64 experimental mode with this is that the lib fails to load. and NVAPI logs "No implementation" (due to NVML not working) for those calls using NVML, and NVML logs:
> 
> ```
> trace:nvml:DLLMain (6ECC0000, 1, 00000000)
> trace:nvml:DLLMain (6ECC0000, 0, 00000000)
> ```
> 
> This is due to 32-bit nvml.so is not loaded. (Checking with strace confirms no attempt to load nvml.so in this wow64 mode).

That's fine, in that case everything more or less works just as expected.

> And i guess you are very right about this being a LOT of the NVML calls using pointers in general, and will probably need conversion. Maybe it is easier to use the script to generate a custom `wow64_nvml_private.h` header file with `ULONG` pointers like Wine seem to have done for their seperate "params" usage? So it is more automated, but not adding ALL the calls that much of a manual labor?

Properly generating such a header can be problematic. Let's take a look at some sample NVML structs:

```c
typedef struct
{
    unsigned int metricId;   //!<  IN: NVML_GPM_METRIC_? #define of which metric to retrieve
    nvmlReturn_t nvmlReturn; //!<  OUT: Status of this metric. If this is nonzero, then value is not valid
    double value;            //!<  OUT: Value of this metric. Is only valid if nvmlReturn is 0 (NVML_SUCCESS)
    struct
    {
        char *shortName;
        char *longName;
        char *unit;
    } metricInfo;            //!< OUT: Metric name and unit. Those can be NULL if not defined
} nvmlGpmMetric_t;

typedef struct
{
    unsigned int version;                              //!< IN: Set to NVML_GPM_METRICS_GET_VERSION
    unsigned int numMetrics;                           //!< IN: How many metrics to retrieve in metrics[]
    nvmlGpmSample_t sample1;                           //!< IN: Sample buffer
    nvmlGpmSample_t sample2;                           //!< IN: Sample buffer
    nvmlGpmMetric_t metrics[NVML_GPM_METRIC_MAX];      //!< IN/OUT: Array of metrics. Set metricId on call. See nvmlReturn and value on return
} nvmlGpmMetricsGet_t;
```

In 32-bit userspace, `sample1` and `sample2` will be 4 bytes each and `nvmlGpmMetric_t` will be 32 bytes while in 64-bit userspace (plus Unixlib side of things) samples will be 8 bytes each and metrics will be 40 bytes each, making this entire struct 3152 bytes on 32-bit and 3944 bytes on 64-bit. To properly read it, we would have to define structures like so:

```c
typedef struct
{
    unsigned int metricId;   //!<  IN: NVML_GPM_METRIC_? #define of which metric to retrieve
    nvmlReturn_t nvmlReturn; //!<  OUT: Status of this metric. If this is nonzero, then value is not valid
    double value;            //!<  OUT: Value of this metric. Is only valid if nvmlReturn is 0 (NVML_SUCCESS)
    struct
    {
        PTR32 shortName;
        PTR32 longName;
        PTR32 unit;
    } metricInfo;            //!< OUT: Metric name and unit. Those can be NULL if not defined
} nvmlGpmMetric_t_32;

typedef struct
{
    unsigned int version;                              //!< IN: Set to NVML_GPM_METRICS_GET_VERSION
    unsigned int numMetrics;                           //!< IN: How many metrics to retrieve in metrics[]
    PTR32 sample1;                                     //!< IN: Sample buffer
    PTR32 sample2;                                     //!< IN: Sample buffer
    nvmlGpmMetric_t_32 metrics[NVML_GPM_METRIC_MAX];   //!< IN/OUT: Array of metrics. Set metricId on call. See nvmlReturn and value on return
} nvmlGpmMetricsGet_t_32;
```

And in `wow64_nvmlGpmMetricsGet` unixlib handler, interpret parameter `nvmlGpmMetricsGet_t *metricsGet` as if it was of type `nvmlGpmMetricsGet_t_32`, allocate and fill our own `nvmlGpmMetricsGet_t`, pass _that_ to native `libnvidia-ml.so`, then copy results from our `nvmlGpmMetricsGet_t` back to the original `nvmlGpmMetricsGet_t_32` before returning. That sounds horrible, even if we were to automate this _somehow_.

**Comment by SveSop** [comment]
That does sound horrible... I am not entirely sure how wine does things on the native lib usage of things like opengl32 and such? There are still a few wine libs that needs 64-bit linux libs, and for those with < 20 functions its not a huge issue, but for libs like opengl32, it is also using automation with a make script + loads 64-bit libgl_somethingorother.so ...

Will hack around and see what comes up, but my severe lack of programming skills really comes short when it comes to these things 😞

**Comment by Saancreed** [comment]
Winevulkan code will probably be a better source of inspiration for this, but on the other hand it's quite enormous in size, so I guess it's a "pick your poison" situation. Having an XML that provides definitions of all the structures is surely helpful there, and I can't really imagine parsing a C header file using only a simple shell script :weary:

In any case, good luck, you will probably need it :sweat_smile:

**Comment by SveSop** [comment]
I updated the https://github.com/SveSop/wine-nvml/tree/wow64 branch and i verified that when running in wow64 mode, the `wow64_` functions are being used instead of the `wine_`  functions.

So.. since i am a bit iffy when it comes to the stuff you use for eg. `print_format` `parse_args` and stuff like that, would it be possible to modify this and use eg. `parse_wow64_args` or something with `params_allargnames` to "convert" stuff for the _params in `nvml_private.h`?

I mean.. i surely will spend 3-4 days over something you would spend 2 seconds figuring out 🐸 

Then again... maybe this should be limited to the calls that DXVK-NVML uses, and just silently drop everything else on the 32-bit side?
Atleast a bit more manageable size:
```
#define GETPROCADDR(x) m_##x = GetProcAddress<decltype(&x)>(#x)

        GETPROCADDR(nvmlInit_v2);
        GETPROCADDR(nvmlShutdown);
        GETPROCADDR(nvmlErrorString);
        GETPROCADDR(nvmlDeviceGetHandleByPciBusId_v2);
        GETPROCADDR(nvmlDeviceGetPciInfo_v3);
        GETPROCADDR(nvmlDeviceGetClockInfo);
        GETPROCADDR(nvmlDeviceGetMaxClockInfo);
        GETPROCADDR(nvmlDeviceGetTemperature);
        GETPROCADDR(nvmlDeviceGetThermalSettings);
        GETPROCADDR(nvmlDeviceGetPerformanceState);
        GETPROCADDR(nvmlDeviceGetUtilizationRates);
        GETPROCADDR(nvmlDeviceGetVbiosVersion);
        GETPROCADDR(nvmlDeviceGetCurrPcieLinkWidth);
        GETPROCADDR(nvmlDeviceGetIrqNum);
        GETPROCADDR(nvmlDeviceGetNumGpuCores);
        GETPROCADDR(nvmlDeviceGetBusType);
        GETPROCADDR(nvmlDeviceGetDynamicPstatesInfo);

#undef GETPROCADDR
```

**Comment by Saancreed** [comment]
Limiting ourselves to just the functions called by dxvk-nvapi is an idea, and certainly something to start with, I'm just not sure if this will get us anywhere and if it won't be a maintainance nightmare in the future no matter how implemented. Looking at those functions we have:

* pointers are not problem as long as we are not returning them by-value to 32-bit Windows userspace, e.g. accepting `const char *pciBusId` as a function parameter is not a problem, but having `nvmlDevice_t *device` (which is essentially `void **device`) is because it would cause a value of type `void*` to be returned and that has different size
  * it also means that `const char *nvmlErrorString(nvmlReturn_t result);` is a problem because pointer we receive from 64-bit unix side should be accessible and readable by 32-bit Windows userspace
* `nvmlPciInfo_t`, `nvmlGpuThermalSettings_t`, `nvmlUtilization_t` and `nvmlGpuDynamicPstatesInfo_t` can be passed as-is because they have the same size and layout on 32-bit and 64-bit, which simplifies things a bit
* most `_params` structs will need to be duplicated, we will need wow64 variants for each one that has different size/layout and most of them have `void *nvmlDevice` as their first member
  * it would be easier/safer to just generate this for all of them because we already get a list of parameters and their types while processing the header

I still don't know how to tackle wrapping and unwrapping `nvmlDevice_t` values but _assuming_ we figure it out somehow, a sample function would probably look like this:

```c
struct nvmlDeviceGetPciInfo_v3_params_wow64
{
    PTR32 device;
    PTR32 pci;
    nvmlReturn_t _result;
};

static NTSTATUS wow64_nvmlDeviceGetPciInfo_v3(void *args)
{
    NTSTATUS status;
    struct nvmlDeviceGetPciInfo_v3_params_wow64 *params32 = args;
    struct nvmlDeviceGetPciInfo_v3_params params64 = { MAGIC_UNWRAP_HANDLE(params32->device), ULongToPtr(params32->pci), 0 };

    if (!(status = wine_nvmlDeviceGetPciInfo_v3(&params64))) /* hopefully we are allowed to call an unixcall handler from another handler */
        params32->_result = params64._result;

    return status;
}
```

Where the implementation of `MAGIC_UNWRAP_HANDLE` is left as an exercise for the reader. I truly think this is not worth the effort :disappointed:

**Comment by Saancreed** [comment]
With #16 merged I suppose I can now close this as no longer relevant.
